version: 2
jobs:
  sytestpy2postgresmerged:
    docker:
      - image: matrixdotorg/sytest-synapse:dinsic
    working_directory: /src
    steps:
      - checkout
      - run: bash .circleci/merge_base_branch.sh
      - run: POSTGRES=1 /synapse_sytest.sh
      - store_artifacts:
          path: /logs
          destination: logs
      - store_test_results:
          path: /logs

workflows:
  version: 2
  build:
    jobs:
      - sytestpy2postgresmerged:
          filters:
            branches:
              ignore: /develop|master|release-.*/